// src/utils/hdbDogs.js

// HDB approved dog breeds
export const HDB_APPROVED_BREEDS = new Set([
  "Affenpinscher",
  "Australian Silky Terrier",
  "Australian Terrier",
  "Bichon Avanese",
  "Bichon Frise",
  "Bohemian Terrier",
  "Bolognese",
  "Border Terrier",
  "Boston Terrier",
  "Brussels Griffon",
  "Cairn Terrier",
  "Cavalier King Charles Spaniel",
  "Chihuahua",
  "Chinese Crested Dog",
  "Chinese Imperial Chin",
  "Chinese Temple Dog",
  "Coton de Tulear",
  "Czech Terrier",
  "Dachshund",
  "Dandie Dinmont Terrier",
  "English Toy Spaniel",
  "German Hunting Terrier",
  "Griffon Belge",
  "Griffon Brabancon",
  "Hairless Dog",
  "Italian Greyhound",
  "Jack Russell Terrier",
  "Japanese Spaniel (Chin)",
  "Japanese Spitz",
  "Lakeland Terrier",
  "Lhasa Apso",
  "Little Lion Dog",
  "Maltese",
  "Manchester Terrier",
  "Miniature Pinscher",
  "Miniature Schnauzer",
  "Norfolk Terrier",
  "Norwegian Lundehund",
  "Norwich Terrier",
  "Papillon",
  "Pekingese",
  "Pomeranian",
  "Poodle (Toy / Miniature)",
  "Pug",
  "Schipperke",
  "Scottish Terrier",
  "Sealyham Terrier",
  "Shetland Sheepdog",
  "Shih Tzu",
  "Silky Terrier",
  "Small Continental Spaniel",
  "Small English Terrier",
  "Small Spitz",
  "Smooth Fox Terrier",
  "Tibetan Spaniel",
  "Toy Fox Terrier",
  "Toy Terrier",
  "Volpino Italiano",
  "Welsh Terrier",
  "West Highland White Terrier",
  "Wire-Haired Fox Terrier",
  "Yorkshire Terrier"
]);